# Generated by Django 4.0.4 on 2022-05-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docunent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NNI', models.CharField(default='', max_length=70)),
                ('Nom', models.CharField(default='', max_length=200)),
                ('Prenom', models.CharField(default='', max_length=70)),
                ('Sex', models.CharField(default='', max_length=200)),
                ('date_naiss', models.CharField(default='', max_length=70)),
                ('dateValidie', models.CharField(default='', max_length=200)),
                ('Pays', models.CharField(default='', max_length=70)),
                ('typeDocument', models.CharField(default='', max_length=200)),
                ('NumeroDocument', models.CharField(default='', max_length=70)),
                ('Path', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
